### ISSUE TITLE
Its broken

### ISSUE THREAD

**Issue by DonaldTsang** [cryptofuture/PassCard#2]
Does not work on redmi note.
The card did not display no matter what I do, and the settings are unusable too.

**Comment by cryptofuture** [comment]
Could you add screenshoot? If you see blank page that means you have gl/gles problems on your device. Actually I thinking about app rewriting with native gui.

**Comment by norrinr** [comment]
![screenshot_2015-10-30-09-02-55](https://cloud.githubusercontent.com/assets/4553848/10850886/3476df5c-7ee5-11e5-837f-453ba4471bfe.png)

**Comment by norrinr** [comment]
Neither the generate button nor the Settings in menu do anything.

**Comment by ujinv** [comment]
Confirm on android 6

**Comment by passcard4android** [comment]
I really trying to fix it: https://stackoverflow.com/questions/35013090/canvas-image-did-not-show-in-android-since-4-4-4
 And I have idea about some new features and want to optimize layouts for different resolution devices.  
But I'm stuck here. Maybe bad idea with ticket in chromium database was not bad as I first thought.

**Comment by cryptofuture** [comment]
Should be fixed in 1.1.
