### ISSUE TITLE
Generate does nothing. Version 1.1

### ISSUE THREAD

**Issue by cvzi** [cryptofuture/PassCard#3]
When I click on _Generate_ nothing happens. The canvas stays blank. Logcat is empty.
I am running Android 4.4.2 (API 19)

**Comment by cryptofuture** [comment]
Thing that I scared about just happened. Are you sure that you running version 1.1? (application icon should just like on current screen on github)
F-Droid reports that application update was 2016-03-11? but really it was builded lately. 
Anyway thanks for report, I will look in 4.4.2 webview rendering.

**Comment by cvzi** [comment]
It's definitely 1.1, I reinstalled to make sure.
(Just to be clear: Version 1.0 from F-droid does not work either).

**Comment by cryptofuture** [comment]
Thanks, hope I'll be able to figure out this. passwordcard.js rendering differently on various chromium versions, but always worked till Webview was based on webkit.

**Comment by dkuku** [comment]
the same problem on my phone running latest miui dev - based on android 5.0.2

**Comment by cryptofuture** [comment]
@cvzi @dkuku Can you test last version build from [here](https://hda.me/PassCard.apk)? (it will be signed with my key, not with F-droid key)

Looks like f-droid checks releases tags on github, but not a release version in Android manifest (and version still not updated with last fixes). And since is not wise to push version with minor updates to f-droid anyway, if it not fixes the issue... Will be great to test it directly first. I tested it myself and webview should render now on devices with hw acceleration problems, or custom Webview without canvas acceleration. But it still not working on another devices, while working on emulator with same API version.

> WebView rendering still stops on some devices on string:
if (getRawPixels(s.width) != t[0] || getRawPixels(s.height) != t[1]) return;

**Comment by cvzi** [comment]
It does not work for me. It does stop at the line that you mentioned.

**Comment by cryptofuture** [comment]
Can you test [this](https://hda.me/PassCard.apk) build, please? (it will be signed with my key, not with F-droid key)
I bet it will work.

**Comment by cvzi** [comment]
It works!

**Comment by cryptofuture** [comment]
Cool. I closing issue then. I think update will be available in 3 days with F-droid. (sometimes faster)
